# Server Dockerfile for Node.js
FROM node:16

WORKDIR /app

# Install dependencies
COPY ./package.json /app
COPY ./package-lock.json /app
RUN npm install

# Copy the rest of the server code
COPY . /app

# Expose the server port
EXPOSE 5000

# Run the server in development mode
CMD ["npm","start"]
